-- DROP DATABASE IF EXISTS UNIVERSAL_COURSE_SEARCH;
-- CREATE DATABASE UNIVERSAL_COURSE_SEARCH;
-- USE UNIVERSAL_COURSE_SEARCH;

CREATE TABLE SCHOOL (
	School_Num	VARCHAR(10)	NOT NULL,
	School_Name	VARCHAR(100)	NOT NULL,
	School_Website	VARCHAR(255),
CONSTRAINT SCHOOL_KEY
	PRIMARY KEY (School_Num)
    );

CREATE TABLE FOCUS (
	 Focus_ID	VARCHAR(10)	NOT NULL,
	 Focus_Name	VARCHAR(50)	NOT NULL,
CONSTRAINT FOCUS_KEY
	 PRIMARY KEY (Focus_ID),
	 UNIQUE (Focus_Name)
     );

CREATE TABLE COURSE (
	Course_ID	INT	NOT NULL,
	School_Num	VARCHAR(10)	NOT NULL,
	Course_Num	VARCHAR(10)	NOT NULL,
	Course_Name	VARCHAR(50),
	Focus_ID	VARCHAR(10)	NOT NULL,
	Course_Link	VARCHAR(255),
CONSTRAINT COURSE_KEY
	PRIMARY KEY (Course_ID),
	FOREIGN KEY (School_Num) REFERENCES SCHOOL (School_Num)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
 	FOREIGN KEY (Focus_ID) REFERENCES FOCUS (Focus_ID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE
    );

CREATE TABLE TOPIC (
	 Course_ID	INT	NOT NULL,
	 Topic_ID	VARCHAR(10)	NOT NULL,
	 Topic	VARCHAR(50)	NOT NULL,
CONSTRAINT TOPIC_KEY
	 PRIMARY KEY (Course_ID, Topic_ID),
	 FOREIGN KEY (Course_ID) REFERENCES COURSE (Course_ID)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION
	 );

CREATE TABLE TOOLS (
	 Course_ID	INT	NOT NULL,
	 Tool_Name	VARCHAR(50)	NOT NULL,
CONSTRAINT TOOLS_KEY
	 PRIMARY KEY (Course_ID, Tool_Name),
	 FOREIGN KEY (Course_ID) REFERENCES COURSE (Course_ID)
     );
