LOAD DATA LOCAL INFILE 'school.csv'
INTO TABLE SCHOOL
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(School_Num, School_Name, School_Website);

LOAD DATA LOCAL INFILE 'focus.csv'
INTO TABLE FOCUS
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(Focus_ID, Focus_Name);

LOAD DATA LOCAL INFILE 'course.csv'
INTO TABLE COURSE
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(Course_ID, School_Num, Course_Num, Course_Name, Focus_ID, Course_Link);

LOAD DATA LOCAL INFILE 'topic.csv'
INTO TABLE TOPIC
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(Course_ID, Topic_ID, Topic);

LOAD DATA LOCAL INFILE 'tools.csv'
INTO TABLE TOOLS
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(Course_ID, Tool_Name);
